name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: pandoc pandoc-citeproc texlive-full
          version: 1.0
      - name: Build
        run: |
          find . -name '*.md' -exec pandoc -f markdown -t pdf {} \;
      - name: Upload
        run: |
          git config user.email "tgrothe@users.noreply.github.com"
          git config user.name "tgrothe"
          git add .
          git commit -m "Msg"
          git push
